-- MySQL Script generated by MySQL Workbench
-- Wed May 10 11:05:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MovimentoCaixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovimentoCaixa` (
  `idMovimentoCaixa` INT NOT NULL AUTO_INCREMENT,
  `data_movimento` DATE NULL,
  `hora_movimento` TIME NULL,
  `descricao` VARCHAR(45) NULL,
  `tipo_movimento` VARCHAR(45) NULL,
  `valor` REAL NULL,
  `MovimentoCaixacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idMovimentoCaixa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf_cnpj` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(10) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `quantidade_estoque` INT NULL,
  `preco` REAL NULL,
  `unidade` VARCHAR(45) NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `Fornecedor_idFornecedor`),
  INDEX `fk_Produto_Fornecedor_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `hora` TIME NULL,
  `total_compra` REAL NULL,
  `situacao_compra` VARCHAR(10) NULL,
  PRIMARY KEY (`idCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itemCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itemCompra` (
  `Compra_idCompra` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Produto_Fornecedor_idFornecedor` INT NOT NULL,
  `quantidade` INT NULL,
  `valor_unitario` REAL NULL,
  `total_item` REAL NULL,
  PRIMARY KEY (`Compra_idCompra`, `Produto_idProduto`, `Produto_Fornecedor_idFornecedor`),
  INDEX `fk_Compra_has_Produto_Produto1_idx` (`Produto_idProduto` ASC, `Produto_Fornecedor_idFornecedor` ASC) VISIBLE,
  INDEX `fk_Compra_has_Produto_Compra1_idx` (`Compra_idCompra` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_has_Produto_Compra1`
    FOREIGN KEY (`Compra_idCompra`)
    REFERENCES `mydb`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto` , `Produto_Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Produto` (`idProduto` , `Fornecedor_idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cpf_cnpj` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(10) NULL,
  `telefone` VARCHAR(20) NULL,
  `emai` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FormaPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FormaPagamento` (
  `idFormaPagamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idFormaPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `hora` TIME NULL,
  `total_venda` REAL NULL,
  `situacao_venda` VARCHAR(8) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `FormaPagamento_idFormaPagamento` INT NOT NULL,
  PRIMARY KEY (`idVenda`, `Cliente_idCliente`, `FormaPagamento_idFormaPagamento`),
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Venda_FormaPagamento1_idx` (`FormaPagamento_idFormaPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_FormaPagamento1`
    FOREIGN KEY (`FormaPagamento_idFormaPagamento`)
    REFERENCES `mydb`.`FormaPagamento` (`idFormaPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemVenda` (
  `Venda_idVenda` INT NOT NULL,
  `Venda_Cliente_idCliente` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `quantidade` INT NULL,
  `valor_unitario` REAL NULL,
  `total_item` REAL NULL,
  PRIMARY KEY (`Venda_idVenda`, `Venda_Cliente_idCliente`, `Produto_idProduto`),
  INDEX `fk_Venda_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Venda_has_Produto_Venda1_idx` (`Venda_idVenda` ASC, `Venda_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_has_Produto_Venda1`
    FOREIGN KEY (`Venda_idVenda` , `Venda_Cliente_idCliente`)
    REFERENCES `mydb`.`Venda` (`idVenda` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conta_Pagar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conta_Pagar` (
  `idConta_Pagar` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `data_lancamento` DATE NULL,
  `data_vencimento` DATE NULL,
  `valor` REAL NULL,
  `pago` VARCHAR(3) NULL,
  `data_pagamento` DATE NULL,
  `valor_pagamento` REAL NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`idConta_Pagar`, `Fornecedor_idFornecedor`),
  INDEX `fk_Conta_Pagar_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Conta_Pagar_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conta_Receber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conta_Receber` (
  `idConta_Receber` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `data_lancamento` DATE NULL,
  `data_vencimento` DATE NULL,
  `valor` REAL NULL,
  `pago` VARCHAR(3) NULL,
  `data_pagamento` DATE NULL,
  `valor_pagamento` REAL NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idConta_Receber`, `Cliente_idCliente`),
  INDEX `fk_Conta_Receber_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Conta_Receber_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovimentoCaixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovimentoCaixa` (
  `idMovimentoCaixa` INT NOT NULL AUTO_INCREMENT,
  `data_movimento` DATE NULL,
  `hora_movimento` TIME NULL,
  `descricao` VARCHAR(45) NULL,
  `tipo_movimento` VARCHAR(45) NULL,
  `valor` REAL NULL,
  `MovimentoCaixacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idMovimentoCaixa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caixa` (
  `idCaixa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `saldo` REAL NULL,
  `Venda_idVenda` INT NOT NULL,
  `MovimentoCaixa_idMovimentoCaixa` INT NOT NULL,
  PRIMARY KEY (`idCaixa`, `Venda_idVenda`, `MovimentoCaixa_idMovimentoCaixa`),
  INDEX `fk_Caixa_Venda1_idx` (`Venda_idVenda` ASC) VISIBLE,
  INDEX `fk_Caixa_MovimentoCaixa1_idx` (`MovimentoCaixa_idMovimentoCaixa` ASC) VISIBLE,
  CONSTRAINT `fk_Caixa_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `mydb`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caixa_MovimentoCaixa1`
    FOREIGN KEY (`MovimentoCaixa_idMovimentoCaixa`)
    REFERENCES `mydb`.`MovimentoCaixa` (`idMovimentoCaixa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
